#!/bin/bash

set -e

echo "What is your project name?"
read Project_Name

echo "What is your repo SSH?"
read Repo_Name

cd ~/workspace

mkdir "${Project_Name}-api"
cd "${Project_Name}-api"

pipenv install django djangorestframework django-cors-headers pillow python-dotenv pylint pylint-django autopep8

pipenv run django-admin startproject "$Project_Name" .

pipenv run python3 manage.py startapp "${Project_Name}API"

# git ignore
curl 'https://raw.githubusercontent.com/github/gitignore/master/Python.gitignore' > .gitignore

# Django Settings
cat > "$Project_Name"/settings.py <<- 'EOF'
"""
Django settings for ${Project_Name} project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "False") == "True"

ALLOWED_HOSTS = [
    host.strip() for host in os.getenv("ALLOWED_HOSTS", "localhost").split(",")
]

# Application definition
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework.authtoken",
    "corsheaders",
    "${Project_Name}API",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

REST_FRAMEWORK = {
    # Authentication
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication"
    ],
    # Permissions
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticatedOrReadOnly",
    ],
    # Pagination
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 10,
    # Filtering
    "DEFAULT_FILTER_BACKENDS": [
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
    # Renderer classes (response format)
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
        "rest_framework.renderers.BrowsableAPIRenderer",  # Nice web UI for development
    ],
}


ROOT_URLCONF = "${Project_Name}.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "${Project_Name}.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

db_name = os.getenv("DB_NAME", "db.sqlite3")

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / db_name,
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

CORS_ALLOWED_ORIGINS = [
    origin.strip()
    for origin in os.getenv("CORS_ORIGINS", "http://localhost:3000").split(",")
]

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# Media Files
MEDIA_URL = os.getenv("MEDIA_URL", "/media/")
ROOT = os.getenv("MEDIA_ROOT", "media")
MEDIA_ROOT = os.path.join(BASE_DIR, ROOT)


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

EOF

# Cross-platform sed
if [[ "$OSTYPE" == "darwin"* ]]; then
    sed -i '' "s/\${Project_Name}/$Project_Name/g" "$Project_Name"/settings.py
else
    sed -i "s/\${Project_Name}/$Project_Name/g" "$Project_Name"/settings.py
fi

SECRET_KEY=$(pipenv run python -c 'from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())')

# ENV File
cat > .env << EOF
SECRET_KEY="$SECRET_KEY"
DEBUG=True
ALLOWED_HOSTS=localhost,127.0.0.1
DB_NAME=db.sqlite3
CORS_ORIGINS=http://localhost:3000,http://localhost:5173
MEDIA_URL=/media/
MEDIA_ROOT=media
EOF

# Folder Structure
rm "${Project_Name}API/models.py"
rm "${Project_Name}API/tests.py"
rm "${Project_Name}API/views.py"

mkdir -p "${Project_Name}API/models" \
    "${Project_Name}API/views" \
    "${Project_Name}API/fixtures" \
    "${Project_Name}API/tests"

touch "${Project_Name}API/models/__init__.py" \
    "${Project_Name}API/views/__init__.py" \
    "${Project_Name}API/tests/__init__.py"


# Initial Users and Tokens Fixtures
cat > "${Project_Name}API/fixtures/users.json" << "EOF"
[
    {
        "model": "auth.user",
        "pk": 1,
        "fields": {
        "password": "pbkdf2_sha256$600000$VQhNLlVPJ0pLKjI3ODkw$LZ8FqN4RmN9K8kQ0yJ8P5qH2vN1xL3mR4tW6sD9fE8Y=",
        "last_login": null,
        "is_superuser": true,
        "username": "admin",
        "first_name": "Admin",
        "last_name": "User",
        "email": "admin@example.com",
        "is_staff": true,
        "is_active": true,
        "date_joined": "2024-01-01T00:00:00Z",
        "groups": [],
        "user_permissions": []
        }
    },
    {
        "model": "auth.user",
        "pk": 2,
        "fields": {
        "password": "pbkdf2_sha256$600000$VQhNLlVPJ0pLKjI3ODkw$LZ8FqN4RmN9K8kQ0yJ8P5qH2vN1xL3mR4tW6sD9fE8Y=",
        "last_login": null,
        "is_superuser": false,
        "username": "john_doe",
        "first_name": "John",
        "last_name": "Doe",
        "email": "john@example.com",
        "is_staff": false,
        "is_active": true,
        "date_joined": "2024-01-15T10:30:00Z",
        "groups": [],
        "user_permissions": []
        }
    },
    {
        "model": "auth.user",
        "pk": 3,
        "fields": {
        "password": "pbkdf2_sha256$600000$VQhNLlVPJ0pLKjI3ODkw$LZ8FqN4RmN9K8kQ0yJ8P5qH2vN1xL3mR4tW6sD9fE8Y=",
        "last_login": null,
        "is_superuser": false,
        "username": "jane_smith",
        "first_name": "Jane",
        "last_name": "Smith",
        "email": "jane@example.com",
        "is_staff": false,
        "is_active": true,
        "date_joined": "2024-01-20T14:45:00Z",
        "groups": [],
        "user_permissions": []
        }
    }
]
EOF

cat > "${Project_Name}API/fixtures/tokens.json" << "EOF"
[
    {
        "model": "authtoken.token",
        "pk": 1,
        "fields": {
        "user": 1,
        "key": "9944b09199c62bcf9418ad846dd0e4bbdfc6ee4b",
        "created": "2024-01-01T00:00:00Z"
        }
    },
    {
        "model": "authtoken.token",
        "pk": 2,
        "fields": {
        "user": 2,
        "key": "a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0",
        "created": "2024-01-15T10:30:00Z"
        }
    },
    {
        "model": "authtoken.token",
        "pk": 3,
        "fields": {
        "user": 3,
        "key": "z9y8x7w6v5u4t3s2r1q0p9o8n7m6l5k4j3i2h1g0",
        "created": "2024-01-20T14:45:00Z"
        }
    }
]
EOF

# Migrations And Load Data

pipenv run python3 manage.py migrate

pipenv run python3 manage.py loaddata users tokens

cat > seed.sh << EOF
#!/bin/bash

if [ -f db.sqlite3 ]
then
        rm db.sqlite3
fi

if [ -d "./${Project_Name}API/migrations" ]
then
        rm -rf "./${Project_Name}API/migrations"
fi

python3 manage.py makemigrations "${Project_Name}API"
python3 manage.py migrate
EOF

chmod +x seed.sh

# URLS
cat > "${Project_Name}/urls.py" << EOF
"""
URL configuration for $Project_Name project.

The \`urlpatterns\` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/6.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""

from django.contrib import admin
from django.urls import path, include
from rest_framework.routers import SimpleRouter

router = SimpleRouter(trailing_slash=False)

urlpatterns = [
    path("", include(router.urls)),
    path("admin/", admin.site.urls),
]
EOF

# GIT
# git init
# git remote add origin $Repo_Name
# git branch -M main
# git add .
# git commit -m 'initial commit'
# git push -u origin main


echo ""
echo "✅ Project setup complete!"
echo ""
echo "Test credentials:"
echo "  Admin: admin / password123"
echo "  Token: 9944b09199c62bcf9418ad846dd0e4bbdfc6ee4b"
echo ""
echo "Next steps:"
echo "  cd ${Project_Name}-api"
echo "  pipenv shell"
echo "  python manage.py runserver"