set -e #exit on any error

echo "what is your project name?"
read Project_Name

echo "what is your repo's SSH?"
read Repo_Name


cd ~/workspace

if [ -d ~/workspace/"${Project_Name}-client" ]
then 
    echo "${Project_Name}-client already exists"
    exit 1
fi

# Next Setup
npx create-next-app@latest "${Project_Name}-client" \
    --typescript \
    --tailwind \
    --eslint \
    --app \
    --src-dir \
    --import-alias "@/*" \
    --no-git

cd "${Project_Name}-client"

# Preferred Plugins 
npm install -D \
    prettier \
    prettier-plugin-tailwindcss \
    eslint-config-prettier

npm install @tanstack/react-query @tanstack/react-query-devtools

# Font Awesome Core packages
npm install @fortawesome/fontawesome-svg-core @fortawesome/react-fontawesome

# Icon packages 
npm install @fortawesome/free-solid-svg-icons
npm install @fortawesome/free-regular-svg-icons
npm install @fortawesome/free-brands-svg-icons

# Remove Default Files
rm -rf public/*

rm -rf src/app/favicon.ico

# Override Home Page
cat > src/app/page.tsx << 'EOF'
export default function Home() {
    return <div></div>
}
EOF

# Make Directories

mkdir -p "src/app/(auth)" \
    "src/app/(auth)/login" \
    "src/app/(auth)/register" \
    src/components \
    src/components/nav \
    src/types \
    src/data \
    src/hooks \
    src/utility \
    public/images \
    public/svg

# Setup NavBar
cat > src/components/nav/NavBar.tsx << 'EOF'
export default function NavBar() {
    return <ul></ul>
}
EOF

# Setup TanStackQuery
cat > src/app/providers.tsx << 'EOF'
"use client"
import React, { useState } from "react"
import { QueryClient, QueryClientProvider } from "@tanstack/react-query"
import { ReactQueryDevtools } from "@tanstack/react-query-devtools"

export default function Providers({ children }: { children: React.ReactNode }) {
    const [queryClient] = useState(() => new QueryClient())
    return (
        <QueryClientProvider client={queryClient}>
            {children}
            {process.env.NODE_ENV === "development" && (
                <ReactQueryDevtools initialIsOpen={false} />
            )}
        </QueryClientProvider>
    )
}
EOF

cat > src/app/layout.tsx << 'EOF'
import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"
import Providers from "./providers"
import NavBar from "@/components/nav/NavBar"

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"]
})

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"]
})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app"
}

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} flex min-h-screen justify-center antialiased`}
            >
                <NavBar />
                <Providers>{children}</Providers>
            </body>
        </html>
    )
}
EOF


# Configs
cat > .prettierrc << 'EOF'
{
    "arrowParens": "always",
    "tabWidth": 4,
    "experimentalTernaries": true,
    "semi": false,
    "trailingComma": "none",
    "bracketSpacing": true,
    "plugins": ["prettier-plugin-tailwindcss"]
}
EOF

cat > eslint.config.mjs << 'EOF'
import { defineConfig, globalIgnores } from "eslint/config"
import nextVitals from "eslint-config-next/core-web-vitals"
import nextTs from "eslint-config-next/typescript"
import prettier from "eslint-config-prettier"

const eslintConfig = defineConfig([
    ...nextVitals,
    ...nextTs,
    prettier,
    // Override default ignores of eslint-config-next.
    globalIgnores([
        // Default ignores of eslint-config-next:
        ".next/**",
        "out/**",
        "build/**",
        "next-env.d.ts"
    ])
])

export default eslintConfig
EOF


# GIT Setup

# git init

cat > .gitignore << 'EOF'
# See https://help.github.com/articles/ignoring-files/ for more about ignoring files.

# dependencies
/node_modules
/.pnp
.pnp.*
.yarn/*
!.yarn/patches
!.yarn/plugins
!.yarn/releases
!.yarn/versions

# testing
/coverage

# next.js
/.next/
/out/

# production
/build

# misc
.DS_Store
*.pem

# debug
npm-debug.log*
yarn-debug.log*
yarn-error.log*
.pnpm-debug.log*

# env files (can opt-in for committing if needed)
.env*

# vercel
.vercel

# typescript
*.tsbuildinfo
next-env.d.ts

#vs code
/.vscode/
EOF

# git remote add origin "${Repo_Name}"
# git branch -M main

# git add .
# git commit -m 'initial commit'
# git push -u origin main



